# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: StormCrawler
email: site@stormcrawler.net
description: > # this means to ignore newlines until "baseurl:"
 StormCrawler is collection of resources for building low-latency, scalable web crawlers on Apache Storm
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stormcrawler.net" # the base hostname & protocol for your site
twitter_username: stormcrawlerapi
github_username:  digitalpebble

# Build settings
markdown: kramdown
